---
kind: pipeline
type: kubernetes
name: amd64

steps:
- name: wait-for-docker
  image: busybox
  volumes:
  - name: dockersock
    path: /var/run
  commands:
  - sleep 5 # give docker enough time to start

- name: test
  image: rancher/dapper:v0.4.1
  volumes:
  - name: dockersock
    path: /var/run
  commands:
  - docker info

services:
- name: docker
  image: docker:18.09-dind
  privileged: true
  entrypoint:
    - "dockerd-entrypoint.sh"
  commands:
    - "--registry-mirror"
    - "https://rxv48fvd.mirror.aliyuncs.com"
  volumes:
  - name: dockersock
    path: /var/run

volumes:
- name: dockersock
  temp: {}