---
kind: pipeline
type: kubernetes
name: amd64

steps:
- name: test
  image: busybox
  volumes:
  - name: dockersock
    path: /var/run
  commands:
  - sleep 5 # give docker enough time to start

- name: test
  image: rancher/dapper:v0.4.1
  volumes:
  - name: dockersock
    path: /var/run
  commands:
  - dapper ci

services:
- name: docker
  image: docker:dind
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run

volumes:
- name: dockersock
  temp: {}